#!/usr/bin/env python3
"""
Erzeugt eine LaTeX-Tabelle mit genauer Beschreibung jeder Variable (Name, Einheit, Beschreibung).
Keine Stationsspalten – nur Variable, Unit, Description.

Eingaben:
  - variables.txt (Variable, Unit, Description)

Ausgabe: essd_clean_variables.tex (booktabs, Gruppenköpfe)
"""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
VARS_SPEC_PATH = SCRIPT_DIR / "variables.txt"
OUTPUT_TEX = SCRIPT_DIR / "essd_clean_variables.tex"

# Variablengruppen für \multicolumn-Köpfe (Reihenfolge der Ausgabe)
VARIABLE_GROUPS = [
    ("Timestamp", ["TIMESTAMP"]),
    ("Eddy-covariance fluxes", ["LE", "LE_QC", "H", "H_QC", "NEE", "CO2_QC", "TAU", "TAU_QC"]),
    ("Radiation and soil heat flux", ["G", "SW_IN", "SW_OUT", "LW_IN", "LW_OUT", "NETRAD"]),
    ("Precipitation and evapotranspiration", ["P", "ET"]),
    ("Auxiliary meteorology", ["PA", "RH", "TA", "VPD", "WD", "WS", "USTAR", "ZL", "MO_LENGHT"]),
    ("Soil profile", ["SWC_1_1_1", "SWC_1_2_1", "SWC_1_3_1", "TS_1_1_1", "TS_1_2_1", "TS_1_3_1"]),
]


def read_variables_spec(path: Path) -> dict[str, tuple[str, str]]:
    """Liest variables.txt; liefert { variable: (unit, description) }."""
    out: dict[str, tuple[str, str]] = {}
    with path.open("r", encoding="utf-8") as f:
        first = True
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if first:
                first = False
                continue
            parts = line.split(",", 2)
            if len(parts) < 2:
                continue
            var = parts[0].strip()
            unit = parts[1].strip()
            desc = (parts[2].strip() if len(parts) > 2 else "").strip()
            if not var:
                continue
            out[var] = (unit, desc)
    return out


def escape_latex(s: str) -> str:
    """Escape für LaTeX (_, %, etc.)."""
    s = s.replace("\\", "\\textbackslash{}")
    s = s.replace("_", "\\_")
    s = s.replace("%", "\\%")
    s = s.replace("&", "\\&")
    s = s.replace("#", "\\#")
    s = s.replace("µ", "\\textmu{}")
    return s


def main() -> None:
    if not VARS_SPEC_PATH.exists():
        print(f"ERROR: variables.txt not found: {VARS_SPEC_PATH}", file=sys.stderr)
        sys.exit(1)

    spec = read_variables_spec(VARS_SPEC_PATH)
    n_cols = 3  # Variable, Unit, Description
    with OUTPUT_TEX.open("w", encoding="utf-8") as f:
        f.write("% Variable descriptions for ESSD 30\\,min clean CSV (generated by make_essd_clean_variables_latex.py)\n")
        f.write("% Requires: \\usepackage{booktabs}\n\n")
        f.write("\\begin{table}[htbp]\n")
        f.write("\\centering\n")
        f.write("\\caption{Overview of variables in the ESSD 30\\,min clean CSV files: name, unit, and description.}\n")
        f.write("\\label{tab:essd_clean_variables}\n")
        f.write("\\begin{tabular}{lll}\n")
        f.write("\\toprule\n")
        f.write("\\textbf{Variable} & \\textbf{Unit} & \\textbf{Description} \\\\\n")
        f.write("\\midrule\n")

        for gi, (group_label, var_names) in enumerate(VARIABLE_GROUPS):
            first_in_group = True
            for var in var_names:
                unit_spec, desc = spec.get(var, ("", ""))
                if not desc:
                    desc = var
                unit = unit_spec or "---"
                desc = desc or "---"
                var_esc = escape_latex(var)
                unit_esc = escape_latex(unit)
                desc_esc = escape_latex(desc)
                if first_in_group:
                    f.write("\\multicolumn{3}{l}{\\textit{" + escape_latex(group_label) + "}} \\\\\n")
                    first_in_group = False
                f.write(f"{var_esc} & {unit_esc} & {desc_esc} \\\\\n")
            if gi < len(VARIABLE_GROUPS) - 1:
                f.write("\\addlinespace\n")

        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table}\n")
    print(f"LaTeX table written: {OUTPUT_TEX}")


if __name__ == "__main__":
    main()
